/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopchanger;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import static javax.swing.JOptionPane.showInputDialog;


/**
 *
 * @author forni
 */
public class ui extends javax.swing.JFrame {

    
    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apply = new java.awt.Button();
        website1label = new java.awt.Label();
        change = new java.awt.Label();
        shuffle = new java.awt.Checkbox();
        website2label = new java.awt.Label();
        website3label = new java.awt.Label();
        website4label = new java.awt.Label();
        website5label = new java.awt.Label();
        website6label = new java.awt.Label();
        changepic = new javax.swing.JComboBox<>();
        website1 = new javax.swing.JTextField();
        website2 = new javax.swing.JTextField();
        website3 = new javax.swing.JTextField();
        website4 = new javax.swing.JTextField();
        website5 = new javax.swing.JTextField();
        website6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallpaper Changer");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("UIframe"); // NOI18N
        setResizable(false);

        apply.setLabel("Apply");
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        website1label.setText("Website 1");

        change.setText("Change picture every...");

        shuffle.setLabel("Shuffle");

        website2label.setText("Website 2");

        website3label.setText("Website 3");

        website4label.setText("Website 4");

        website5label.setText("Website 5");

        website6label.setText("Website 6");

        changepic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 seconds", "30 seconds", "1 minute", "2 minutes", "custom..." }));
        changepic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepicActionPerformed(evt);
            }
        });

        website1.setText("https://media.kron.com/nxs-krontv-media-us-east-1/Traffic/cam3_2_large.jpg");

        website2.setText("https://pixelcaster.com/yosemite/webcams/ahwahnee2.jpg?1599421088520");
        website2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                website2ActionPerformed(evt);
            }
        });

        website3.setText(" https://meredith-cdn.s3.amazonaws.com/kptv/cams/river.jpg");

        website4.setText("https://meredith-cdn.s3.amazonaws.com/kptv/cams/skibowl.jpg ");

        website5.setText("https://meredith-cdn.s3.amazonaws.com/kptv/cams/shriners.jpg");

        website6.setText(" https://meredith-cdn.s3.amazonaws.com/kptv/cams/Seaside.jpg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(website1label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(website2label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(website3label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(website4label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(website5label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(website6label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(website6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(website5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(website2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(website4)
                            .addComponent(website3)
                            .addComponent(website1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changepic, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shuffle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(189, 189, 189)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(website1label, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website2label, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(website3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website3label, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(website4label, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website5label, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(website5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website6label, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(website6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shuffle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changepic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Changes wallpaper with live images");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        int time = 0;
        String websiteone = website1.getText();
        String websitetwo = website2.getText();
        String websitethree = website3.getText();
        String websitefour = website4.getText();
        String websitefive = website5.getText();
        String websitesix = website6.getText();
        String username = System.getProperty("user.name");
        boolean run = true;
        File directory = new File("C://Users/" + username + "/Pictures/Wallpaper Changer/");
        directory.mkdirs();

       super.setVisible(false);
        
       int selectedIndex = changepic.getSelectedIndex();
         if (selectedIndex == 0) {
            time = 10;
        }
        if (selectedIndex == 1) {
            time = 30;
        }
        if (selectedIndex == 2) {
            time = 160;
        }
        if (selectedIndex == 3) {
            time = 120;
        }
        if (selectedIndex == 4) {
            String num = showInputDialog(null, "Enter a time in seconds...");
            time = Integer.parseInt(num);
        }
        
        if (shuffle.getState() == true) {
            Random rand = new Random();
            int upperbound = 7;
            do {
            int int_random = rand.nextInt(upperbound); 
            if (website1.getText() != null && int_random == 1) {
                performactions(website1.getText(), time, username, "wallpaper1.jpg");
            }
            if (website2.getText() != null && int_random == 2) {
                performactions(website2.getText(), time, username, "wallpaper2.jpg");
            }
            if (website3.getText() != null && int_random == 3) {
                performactions(website3.getText(), time, username, "wallpaper3.jpg");
            }
            if (website4.getText() != null && int_random == 4) {
                performactions(website4.getText(), time, username, "wallpaper4.jpg");
            }
            if (website5.getText() != null && int_random == 5) {
                performactions(website5.getText(), time, username, "wallpaper5.jpg");
            }
            if (website6.getText() != null && int_random == 6) {
                performactions(website6.getText(), time, username, "wallpaper6.jpg");
            }

        } while (run);
        }
        do {
            if (website1.getText() != null) {
                performactions(website1.getText(), time, username, "wallpaper1.jpg");
            }
            if (website2.getText() != null) {
                performactions(website2.getText(), time, username, "wallpaper2.jpg");
            }
            if (website3.getText() != null) {
                performactions(website3.getText(), time, username, "wallpaper3.jpg");
            }
            if (website4.getText() != null) {
                performactions(website4.getText(), time, username, "wallpaper4.jpg");
            }
            if (website5.getText() != null) {
                performactions(website5.getText(), time, username, "wallpaper5.jpg");
            }
            if (website6.getText() != null) {
                performactions(website6.getText(), time, username, "wallpaper6.jpg");
            }

        } while (run);


    }//GEN-LAST:event_applyActionPerformed

    private int index(int selectedIndex, int time) {
         if (selectedIndex == 0) {
            time = 10;
        }
        if (selectedIndex == 1) {
            time = 30;
        }
        if (selectedIndex == 2) {
            time = 160;
        }
        if (selectedIndex == 3) {
            time = 120;
        }
        if (selectedIndex == 4) {
            String num = showInputDialog(null, "Enter a time in seconds...");
            time = Integer.parseInt(num);
        }
        return time;
    }
    private void changepicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepicActionPerformed

        
    }//GEN-LAST:event_changepicActionPerformed

    private void website2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_website2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_website2ActionPerformed

    private void performactions(String website, int time, String username, String finalfile) {
        URL url = null;
        try {
            url = new URL(website);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }
        String fileName = url.getFile();
        String destName = "C://Users/" + username + "/Pictures/Wallpaper Changer/" + finalfile;

        InputStream is = null;
        try {
            is = url.openStream();
        } catch (IOException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }
        OutputStream os = null;
        try {
            os = new FileOutputStream(destName);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }

        byte[] b = new byte[2048];
        int length;

        try {
            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }
        } catch (IOException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            is.close();
        } catch (IOException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            os.close();
        } catch (IOException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }

        User32.INSTANCE.SystemParametersInfo(0x0014, 0, "C:\\Users\\" + username + "\\Pictures\\Wallpaper Changer\\" + finalfile, 1);

        try {
            TimeUnit.SECONDS.sleep(time);
        } catch (InterruptedException ex) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button apply;
    private java.awt.Label change;
    private javax.swing.JComboBox<String> changepic;
    private java.awt.Checkbox shuffle;
    private javax.swing.JTextField website1;
    private java.awt.Label website1label;
    private javax.swing.JTextField website2;
    private java.awt.Label website2label;
    private javax.swing.JTextField website3;
    private java.awt.Label website3label;
    private javax.swing.JTextField website4;
    private java.awt.Label website4label;
    private javax.swing.JTextField website5;
    private java.awt.Label website5label;
    private javax.swing.JTextField website6;
    private java.awt.Label website6label;
    // End of variables declaration//GEN-END:variables
}
